<div><x-ui.page-header :title="__('erp.banking.create_transaction')" :description="__('erp.banking.tx_create_hint')" :breadcrumbs="[['label'=>__('erp.nav.banking')],['label'=>__('erp.banking.transactions'),'href'=>route('banking.transactions')],['label'=>__('erp.banking.create_transaction')]]" />
<form wire:submit="save" class="mx-auto max-w-5xl overflow-hidden rounded-lg border border-border bg-card">@error('transaction')<x-ui.alert variant="danger" class="m-5">{{ $message }}</x-ui.alert>@enderror
<x-ui.form-section :title="__('erp.banking.tx_identity')"><x-ui.field :label="__('erp.banking.account')" for="tx-account" required><select id="tx-account" wire:model.live="treasury_account_id" class="erp-control"><option value="">{{ __('erp.banking.select_account') }}</option>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->code }} — {{ app()->getLocale()==='ar'?($a->name_ar??$a->name_en):($a->name_en??$a->name_ar) }}</option>@endforeach</select></x-ui.field>
<x-ui.field :label="__('erp.banking.tx_type')" for="tx-type" required><select id="tx-type" wire:model.live="type" class="erp-control">@foreach($types as $t)<option value="{{ $t->value }}">{{ __('erp.banking.tx_types.'.$t->value) }}</option>@endforeach</select></x-ui.field>
<x-ui.field :label="__('erp.date')" for="tx-date" required><input id="tx-date" type="date" wire:model="transaction_date" class="erp-control" dir="ltr" /></x-ui.field>
<x-ui.field :label="__('erp.amount')" for="tx-amount" required><input id="tx-amount" type="number" min="0.000001" step="0.000001" wire:model="amount" class="erp-control text-end" dir="ltr" /></x-ui.field>
<x-ui.field :label="__('erp.currency')" for="tx-currency" required><input id="tx-currency" wire:model="currency" maxlength="3" class="erp-control uppercase" dir="ltr" /></x-ui.field><x-ui.field :label="__('erp.document.exchange_rate')" for="tx-rate"><input id="tx-rate" type="number" step="0.0000000001" wire:model="exchange_rate" class="erp-control" dir="ltr" /></x-ui.field></x-ui.form-section>
<x-ui.form-section :title="__('erp.banking.counterparty')">@if($type==='transfer')<x-ui.field :label="__('erp.banking.destination_account')" for="tx-destination" required><select id="tx-destination" wire:model="counter_treasury_account_id" class="erp-control"><option value="">{{ __('erp.banking.select_account') }}</option>@foreach($accounts as $a)<option value="{{ $a->id }}">{{ $a->code }} — {{ $a->name_en??$a->name_ar }}</option>@endforeach</select></x-ui.field>@else<x-ui.field :label="__('erp.banking.counter_account')" for="tx-counter" required><select id="tx-counter" wire:model="counter_account_code" class="erp-control">@foreach($counterAccounts as $a)<option value="{{ $a->code }}">{{ $a->code }} — {{ app()->getLocale()==='ar'?$a->name_ar:($a->name_en??$a->name_ar) }}</option>@endforeach</select></x-ui.field>@endif
<x-ui.field :label="__('erp.document.reference')" for="tx-reference"><input id="tx-reference" wire:model="reference" class="erp-control" /></x-ui.field><x-ui.field :label="__('erp.description')" for="tx-description"><input id="tx-description" wire:model="description" class="erp-control" /></x-ui.field></x-ui.form-section>
<x-ui.form-actions :note="__('erp.form.draft_note')"><x-ui.button variant="secondary" :href="route('banking.transactions')">{{ __('erp.cancel') }}</x-ui.button><x-ui.button type="submit">{{ __('erp.banking.save_transaction') }}</x-ui.button></x-ui.form-actions></form></div>
